"""Render an AnalysisResult as the master prompt's A–P markdown report.

Color language follows the output spec (§4): every verdict/severity carries an emoji +
written label so the HTML renderers can color-code deterministically.
"""
from __future__ import annotations

import json
from pathlib import Path

from .models import AnalysisResult

VERDICT_COLOR = {
    "KEEP": "🟢", "PROTECT": "🟢", "ADD": "🟢", "EXPAND": "🟢",
    "TRIM": "🟠", "REFINE": "🟠", "RESTRUCTURE": "🟠",
    "MERGE": "🔵", "MOVE": "🔵", "INTERCUT": "🔵",
    "REMOVE": "🔴", "DELETE": "🔴",
}
SEVERITY_COLOR = {"high": "🔴", "medium": "🟠", "low": "🟡"}


def _colored(token: str) -> str:
    t = (token or "").strip().upper()
    dot = VERDICT_COLOR.get(t) or SEVERITY_COLOR.get(t.lower())
    return f"{dot} {token}" if dot else (token or "—")


def render_report(result: AnalysisResult) -> str:
    b = result.brief
    L: list[str] = []

    def add(item: object) -> None:
        # models sometimes return lists/dicts for scalar fields — never crash the report
        if isinstance(item, str):
            L.append(item)
        elif isinstance(item, (list, tuple)):
            L.append("; ".join(str(x) for x in item))
        elif isinstance(item, dict):
            L.append(", ".join(f"{k}: {v}" for k, v in item.items()))
        else:
            L.append(str(item))

    add(f"# EDIT ANALYSIS — {result.screenplay_title}")
    add("")
    add("> Generated by edit-table · lead agent + scene workers + genre specialists "
        "+ utility workers · reconciled by the lead agent")
    add("")
    add("## Pipeline log")
    add("")
    for s in result.stages:
        add(f"- {s}")
    add("")

    # A–E: global judgment
    add("## A. One-line story")
    add(b.one_line_story or "_n/a_")
    add("\n## B. Core conflict")
    add(b.core_conflict or "_n/a_")
    add("\n## C. Hero arc")
    add(b.hero_arc or "_n/a_")
    add("\n## D. Villain / antagonist arc")
    add(b.antagonist_arc or "_n/a_")
    add("\n## E. Emotional graph")
    add("")
    add("| Position (%) | Energy (0-100) | Beat |")
    add("|---|---|---|")
    for pt in result.emotional_graph:
        if isinstance(pt, dict):
            add(f"| {pt.get('position_pct', '?')} | {pt.get('energy', '?')} | {pt.get('label', '')} |")
        else:
            add(f"| ? | ? | {pt} |")
    add("")

    # Protection + global notes from the lead's brief
    if b.story_priorities:
        add("\n## Story priorities — protect these")
        add("")
        for p in b.story_priorities:
            add(f"- 🟢 {p}")
        add("")
    if b.genre_mix:
        add(f"**Genre mix:** {', '.join(b.genre_mix)}  ")
    if b.emotional_core:
        add(f"**Emotional core:** {b.emotional_core}")
    if b.global_notes:
        add("\n## Global notes from the lead")
        add("")
        for g in b.global_notes:
            add(f"- {g}")
        add("")

    # K–L: runtime & repetition
    util_rt = result.utilities.get("runtime")
    add("## K. Runtime problem")
    add("")
    if util_rt:
        p = util_rt.payload
        add(f"- Estimated current runtime: **~{b.current_runtime_min:.0f} min** → target "
            f"**{b.target_runtime_min:.0f} min**")
        add(f"- Slow zones: {', '.join(p.get('slow_zones', [])) or 'none flagged'}")
        add(f"- Trim candidates: "
            + (", ".join(f"#{c['scene_number']} (−{c.get('est_savings_min', '?')} min)"
                         for c in p.get('trim_candidates', [])) or "none"))
    else:
        add(f"- Estimated runtime ~{b.current_runtime_min:.0f} min (target {b.target_runtime_min:.0f} min)")
    add("\n## L. Repetition problem")
    cont = result.utilities.get("continuity")
    if cont:
        for item in cont.payload.get("unpaid_setups", []):
            add(f"- **Unpaid setup** (scene {item.get('setup_scene')}): {item.get('what_was_set_up')} — {item.get('risk')}")
        for item in cont.payload.get("broken_promises", []):
            add(f"- **Broken promise:** {item}")
    add("")

    # M. Top 10 opportunities
    add("## M. Top editing opportunities")
    add("")
    for i, opp in enumerate(result.top_opportunities[:10], 1):
        add(f"{i}. {opp}")
    add("")

    # N. Scene-by-scene edit table + runtime ledger + protection list
    add("## N. Scene-by-scene edit table")
    add("")
    analyses = {a.scene_number: a for a in result.scene_analyses}
    verdicts = {v.scene_number: v for v in result.final_verdicts}
    add("| Scene | Verdict | Action | Problem class | Safe/Aggressive | Est. min |")
    add("|---|---|---|---|---|---|")
    for n in sorted(set(analyses) | set(verdicts)):
        v = verdicts.get(n)
        a = analyses.get(n)
        est = f"{a.estimated_runtime:.1f}" if a and a.estimated_runtime else ""
        if v:
            add(f"| {n} | **{_colored(v.verdict)}** | {v.action} | "
                f"{a.problem_class if a else ''} | {v.safe_vs_aggressive} | {est} |")
        elif a:
            add(f"| {n} | **{_colored(a.recommended_cut)}** | {a.editing_opportunity} "
                f"| {a.problem_class} | — | {est} |")
    add("")

    # Runtime ledger (spec §7): per-scene accounting in one compact table
    if analyses:
        add("\n## Runtime ledger")
        add("")
        add("| Scene | Current est. | Verdict | Net direction | Confidence |")
        add("|---|---|---|---|---|")
        for n in sorted(analyses):
            a = analyses[n]
            v = verdicts.get(n)
            verdict = v.verdict if v else a.recommended_cut
            direction = {"KEEP": "0", "TRIM": "−", "REMOVE": "−−", "MERGE": "−",
                         "RESTRUCTURE": "±", "MOVE": "0", "ADD": "+", "EXPAND": "+"}.get(
                             (verdict or "").upper(), "?")
            add(f"| {n} | {a.estimated_runtime:.1f} min | {_colored(verdict)} "
                f"| {direction} | {'HIGH' if a.estimated_runtime else 'LOW'} |")
        add("")

    # Protection list (spec §10): what must survive the cut
    protected = [v for v in result.final_verdicts if v.verdict.upper() in ("KEEP", "PROTECT")]
    if protected:
        add("\n## Protection list — must survive any cut")
        add("")
        for v in protected:
            add(f"- 🟢 Scene {v.scene_number}: {v.reason or v.action}")
        add("")

    # Per-scene expandable detail cards with source excerpts
    if analyses:
        add("\n## Scene detail cards")
        add("")
        add("One card per inspected scene. Expand for the full worker judgment + source excerpt.")
        add("")
        for n in sorted(analyses):
            a = analyses[n]
            v = verdicts.get(n)
            verdict = v.verdict if v else a.recommended_cut
            reason = f" — {v.reason}" if v and v.reason else ""
            add("<details>")
            add(f"<summary>Scene {n} · **{_colored(verdict)}**{reason} "
                f"· ~{a.estimated_runtime:.1f} min · {a.problem_class or 'no class'}</summary>")
            add("")
            excerpt = " ".join((result.scene_texts.get(n) or "").split())[:300]
            if excerpt:
                add(f"> {excerpt}{' …' if len(' '.join((result.scene_texts.get(n) or '').split())) > 300 else ''}")
                add("")
            for label, val in [("Purpose", a.scene_purpose), ("Conflict", a.conflict),
                               ("Emotional state", a.emotional_state),
                               ("Audience expectation", a.audience_expectation),
                               ("Scene hook", a.scene_hook),
                               ("Turning point", a.turning_point), ("Payoff", a.payoff),
                               ("Weak point", a.weak_point),
                               ("Editing opportunity", a.editing_opportunity),
                               ("Recommended trim", a.recommended_trim),
                               ("Transition", a.transition),
                               ("BGM requirement", a.bgm_requirement),
                               ("Sound design", a.sound_design), ("Tempo", a.tempo),
                               ("Worker notes", a.notes)]:
                if val:
                    add(f"**{label}.** {val}  ")
            if v:
                add(f"\n**Lead's action.** {v.action}  ")
                add(f"**Safe/aggressive:** {v.safe_vs_aggressive}")
            add("")
            add("</details>")
            add("")

    # O. BGM / tempo map
    add("## O. BGM / tempo map")
    add("")
    bgm = result.utilities.get("bgm_map")
    if bgm:
        add("| Section | BPM | Start | Build | Drop | Silence | Note |")
        add("|---|---|---|---|---|---|---|")
        for m in bgm.payload.get("bgm_map", []):
            if not isinstance(m, dict):
                m = {"section": str(m)}
            add(f"| {m.get('section', '')} | {m.get('tempo_bpm', '')} | {m.get('bgm_start', '')} "
                f"| {m.get('bgm_build', '')} | {m.get('bgm_drop', '')} | {m.get('silence', '')} "
                f"| {m.get('note', '')} |")
    else:
        add("_n/a_")
    add("")

    # Genre findings
    if result.genre_findings:
        add("## Genre specialist findings")
        add("")
        add("| Specialist | Scene | Severity | Finding |")
        add("|---|---|---|---|")
        for f in result.genre_findings:
            add(f"| {f.specialist} | {f.scene_number or '—'} | {f.severity} | {f.finding} |")
        add("")

    # Character arcs
    chars = result.utilities.get("character_arcs")
    if chars:
        add("## Character arcs")
        add("")
        for c in chars.payload.get("characters", []):
            if not isinstance(c, dict):
                c = {"name": str(c)}
            add(f"- **{c.get('name')}** — {c.get('arc')}")
            for mb in c.get("missing_beats", []) or []:
                add(f"  - Missing beat: {mb}")
        add("")

    # Conflicts found in reconciliation
    if result.conflicts:
        add("## Reconciliation — worker contradictions the lead resolved")
        add("")
        for c in result.conflicts:
            add(f"- Scene {c.scene_number}: {c.issue} → **Resolution:** {c.resolution}")
        add("")

    # P. Final edit plan
    add("## P. Final edit plan")
    add("")
    add(result.final_edit_plan or "_n/a_")
    add("")
    add("---")
    add("_Story first → emotion second → character third → rhythm fourth → edit fifth → style last._")
    return "\n".join(L)


def save_outputs(result: AnalysisResult, out_dir: str | Path) -> tuple[Path, Path]:
    out = Path(out_dir) / result.tenant_id   # per-tenant isolation of reports
    out.mkdir(parents=True, exist_ok=True)
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in result.screenplay_title)[:60]
    md = out / f"{safe}_edit_report.md"
    js = out / f"{safe}_edit_report.json"
    md.write_text(render_report(result), encoding="utf-8")
    js.write_text(json.dumps(result.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")
    return md, js
