"""Render an AnalysisResult as the master prompt's A–P markdown report."""
from __future__ import annotations

import json
from pathlib import Path

from .models import AnalysisResult


def render_report(result: AnalysisResult) -> str:
    b = result.brief
    L: list[str] = []
    add = L.append

    add(f"# EDIT ANALYSIS — {result.screenplay_title}")
    add("")
    add("> Generated by madhav-edit · lead agent + scene workers + genre specialists "
        "+ utility workers · reconciled by the lead agent")
    add("")
    add("## Pipeline log")
    add("")
    for s in result.stages:
        add(f"- {s}")
    add("")

    # A–E: global judgment
    add("## A. One-line story")
    add(b.one_line_story or "_n/a_")
    add("\n## B. Core conflict")
    add(b.core_conflict or "_n/a_")
    add("\n## C. Hero arc")
    add(b.hero_arc or "_n/a_")
    add("\n## D. Villain / antagonist arc")
    add(b.antagonist_arc or "_n/a_")
    add("\n## E. Emotional graph")
    add("")
    add("| Position (%) | Energy (0-100) | Beat |")
    add("|---|---|---|")
    for pt in result.emotional_graph:
        add(f"| {pt.get('position_pct', '?')} | {pt.get('energy', '?')} | {pt.get('label', '')} |")
    add("")

    # K–L: runtime & repetition
    util_rt = result.utilities.get("runtime")
    add("## K. Runtime problem")
    add("")
    if util_rt:
        p = util_rt.payload
        add(f"- Estimated current runtime: **~{b.current_runtime_min:.0f} min** → target "
            f"**{b.target_runtime_min:.0f} min**")
        add(f"- Slow zones: {', '.join(p.get('slow_zones', [])) or 'none flagged'}")
        add(f"- Trim candidates: "
            + (", ".join(f"#{c['scene_number']} (−{c.get('est_savings_min', '?')} min)"
                         for c in p.get('trim_candidates', [])) or "none"))
    else:
        add(f"- Estimated runtime ~{b.current_runtime_min:.0f} min (target {b.target_runtime_min:.0f} min)")
    add("\n## L. Repetition problem")
    cont = result.utilities.get("continuity")
    if cont:
        for item in cont.payload.get("unpaid_setups", []):
            add(f"- **Unpaid setup** (scene {item.get('setup_scene')}): {item.get('what_was_set_up')} — {item.get('risk')}")
        for item in cont.payload.get("broken_promises", []):
            add(f"- **Broken promise:** {item}")
    add("")

    # M. Top 10 opportunities
    add("## M. Top editing opportunities")
    add("")
    for i, opp in enumerate(result.top_opportunities[:10], 1):
        add(f"{i}. {opp}")
    add("")

    # N. Scene-by-scene edit table
    add("## N. Scene-by-scene edit table")
    add("")
    add("| Scene | Verdict | Action | Problem class | Safe/Aggressive |")
    add("|---|---|---|---|---|")
    analyses = {a.scene_number: a for a in result.scene_analyses}
    verdicts = {v.scene_number: v for v in result.final_verdicts}
    for n in sorted(set(analyses) | set(verdicts)):
        v = verdicts.get(n)
        a = analyses.get(n)
        if v:
            add(f"| {n} | **{v.verdict}** | {v.action} | "
                f"{a.problem_class if a else ''} | {v.safe_vs_aggressive} |")
        elif a:
            add(f"| {n} | {a.recommended_cut} | {a.editing_opportunity} "
                f"| {a.problem_class} | — |")
    add("")

    # O. BGM / tempo map
    add("## O. BGM / tempo map")
    add("")
    bgm = result.utilities.get("bgm_map")
    if bgm:
        add("| Section | BPM | Start | Build | Drop | Silence | Note |")
        add("|---|---|---|---|---|---|---|")
        for m in bgm.payload.get("bgm_map", []):
            add(f"| {m.get('section', '')} | {m.get('tempo_bpm', '')} | {m.get('bgm_start', '')} "
                f"| {m.get('bgm_build', '')} | {m.get('bgm_drop', '')} | {m.get('silence', '')} "
                f"| {m.get('note', '')} |")
    else:
        add("_n/a_")
    add("")

    # Genre findings
    if result.genre_findings:
        add("## Genre specialist findings")
        add("")
        add("| Specialist | Scene | Severity | Finding |")
        add("|---|---|---|---|")
        for f in result.genre_findings:
            add(f"| {f.specialist} | {f.scene_number or '—'} | {f.severity} | {f.finding} |")
        add("")

    # Character arcs
    chars = result.utilities.get("character_arcs")
    if chars:
        add("## Character arcs")
        add("")
        for c in chars.payload.get("characters", []):
            add(f"- **{c.get('name')}** — {c.get('arc')}")
            for mb in c.get("missing_beats", []):
                add(f"  - Missing beat: {mb}")
        add("")

    # Conflicts found in reconciliation
    if result.conflicts:
        add("## Reconciliation — worker contradictions the lead resolved")
        add("")
        for c in result.conflicts:
            add(f"- Scene {c.scene_number}: {c.issue} → **Resolution:** {c.resolution}")
        add("")

    # P. Final edit plan
    add("## P. Final edit plan")
    add("")
    add(result.final_edit_plan or "_n/a_")
    add("")
    add("---")
    add("_Story first → emotion second → character third → rhythm fourth → edit fifth → style last._")
    return "\n".join(L)


def save_outputs(result: AnalysisResult, out_dir: str | Path) -> tuple[Path, Path]:
    out = Path(out_dir) / result.tenant_id   # per-tenant isolation of reports
    out.mkdir(parents=True, exist_ok=True)
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in result.screenplay_title)[:60]
    md = out / f"{safe}_edit_report.md"
    js = out / f"{safe}_edit_report.json"
    md.write_text(render_report(result), encoding="utf-8")
    js.write_text(json.dumps(result.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")
    return md, js
